x<-c(25,34,22,56,64,46,53,31,26)
cat('\nThe list of values are:\n',x)
#calculate variance using var()
v<-var(x)
cat("\n\n Variance:\t\t",v)
#calculate standards deviation using sd()
s<-sd(x)
  cat("\n Standard Deviation:\t",s)